# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [1]:
import numpy as np

In [2]:
a = np.zeros(100)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2.Создать вектор размера 100, заполненный единицами

In [3]:
a = np.ones(100)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 3.Создать вектор размера 100, заполненный числом 3

In [4]:
a = 3*np.ones(100)
a

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

#### 4. Как получить документацию о функции numpy.add из командной строки?

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 5. Поменять 2 строки в матрице

In [29]:
a = np.eye(3)
a[[0,1]] = a[[1,0]]
a

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

#### 6. Создать вектор со значениями от 10 до 100

In [24]:
a = np.arange(10,100)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

#### 7. Развернуть вектор (первый становится последним)

In [25]:
a[::-1]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [27]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [32]:
a = np.array([1, 2, 3, 4, 5])
z = np.zeros(len(a) + 3*(len(a) - 1))
z[::4] = a
z

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 10. Создать 3x3 единичную матрицу

In [34]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Создать массив 3x3x3 со случайными значениями

In [35]:
a = np.random.rand(3,3,3)
a

array([[[0.08252957, 0.99528841, 0.87305686],
        [0.26332087, 0.83207659, 0.31893676],
        [0.94608855, 0.14761275, 0.89549232]],

       [[0.09819213, 0.45313861, 0.98200945],
        [0.69299188, 0.28612776, 0.19514835],
        [0.64271661, 0.50820387, 0.81429068]],

       [[0.87987571, 0.46615491, 0.42350202],
        [0.53981042, 0.48375444, 0.82193165],
        [0.53648692, 0.59311308, 0.66063245]]])

#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [36]:
g = np.random.rand(100).reshape(10,10)
print(g)
print("min =",g.min())
print("min =",g.max())

[[0.52105966 0.09117976 0.40156516 0.76515425 0.37016119 0.60610608
  0.78788394 0.86207582 0.63066574 0.50190526]
 [0.51138937 0.10145094 0.03161154 0.00824233 0.50420483 0.18927558
  0.8572308  0.31133608 0.63210009 0.29565751]
 [0.18081435 0.47295786 0.98281194 0.6728619  0.1587857  0.74613428
  0.03345262 0.76308649 0.5249826  0.99154169]
 [0.07828803 0.19556941 0.34526244 0.62255823 0.64360809 0.62393666
  0.64169102 0.54459436 0.40630244 0.14433844]
 [0.66604315 0.66879493 0.4167891  0.53580241 0.92943409 0.66747331
  0.33550655 0.08693206 0.21783465 0.67775674]
 [0.67396146 0.8414565  0.35938403 0.06097715 0.27377048 0.97585622
  0.05919495 0.15094443 0.50113591 0.12749977]
 [0.39440187 0.51024546 0.0875637  0.98865199 0.52376718 0.6537909
  0.94675372 0.84881701 0.04400141 0.76658701]
 [0.71572641 0.238909   0.86753429 0.85000909 0.4292823  0.33499463
  0.38951801 0.66477127 0.58802445 0.08551688]
 [0.92194848 0.04021633 0.22859606 0.13463706 0.50433019 0.20914649
  0.56651134 

#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [38]:
a = np.random.rand(30)
a.mean()

0.5414417570614394

#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [46]:
a = np.ones((5,5))
a[1:4, 1:4] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

In [75]:
#ОБРАТНАЯ МАТРИЦА
def minor(a, i, j): #возвращает матрицу а без i-ой строки и j-ого столбца 
    r = np.zeros((a.shape[0]-1,a.shape[1]-1))
    r[:i, :j] = a[:i, :j]
    r[:i, j:] = a[:i, (j+1):]
    r[i:, j:] = a[(i+1):, (j+1):]
    r[i:, :j] = a[(i+1):, :j]
    return r

In [76]:
a = np.array([[1.,1.,0.],[0.,1.,1.],[0.,0.,1.]])
b = np.zeros((3,3))
print("a =",a)
if(np.linalg.det(a)!=0):
    for i in range (a.shape[0]):#находим обратную матрицу
        for j in range (a.shape[1]):
            #формула нахождения обр. матрицы через алгебраические дополнения
            b[i,j] = (1/np.linalg.det(a)) * ((-1)**(i+j))*(np.linalg.det(minor(a,j,i)))
    print("a^(-1) =", b)
    print("Проверка:")
    print("a@a^(-1) =", a@b)

a = [[1. 1. 0.]
 [0. 1. 1.]
 [0. 0. 1.]]
a^(-1) = [[ 1. -1.  1.]
 [-0.  1. -1.]
 [ 0. -0.  1.]]
Проверка:
a@a^(-1) = [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [48]:
a = np.diag(np.arange(1, 5), k=-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [51]:
a = np.zeros((8,8))
a[0::2,0::2] = 1
a[1::2,1::2] = 1
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [65]:
a = np.random.rand(6,7,8)
ind = np.unravel_index(100,a.shape)
print("ind =", ind)
a[ind]

ind = (1, 5, 4)


0.5827766779647937

#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [67]:
a = np.tile(np.array([[1,0],[0,1]]), (4,4))
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 20. Перемножить матрицы 5x3 и 3x2

In [126]:
a = np.random.rand(5,3)
b = np.random.rand(3,2)
c = a @ b
print(c)
c.shape

[[0.86480553 0.3910793 ]
 [1.39839117 0.8534698 ]
 [1.09697045 0.93297987]
 [0.97971124 1.02719067]
 [0.73653394 0.48347261]]


(5, 2)

#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [80]:
a = np.arange(10)
mask = ((a > 3) & (a < 8))
a[mask] = -1
a

array([ 0,  1,  2,  3, -1, -1, -1, -1,  8,  9])

#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [83]:
a = np.tile(np.arange(5), 5).reshape(5,5)
a

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 24. Есть генератор, сделать с его помощью массив

In [89]:
def gen(n):
    for i in range(n):
        yield i
a0 = gen(5)
a = np.fromiter(a0, dtype = int)
a

array([0, 1, 2, 3, 4])

#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [98]:
a = np.linspace(0,1,12)
b = a[1:11]
b

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 26. Отсортировать вектор

In [100]:
a = np.linspace(0,1,12)
a.sort()
a

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

#### 27. Проверить, одинаковы ли 2 numpy массива

In [110]:
a = np.arange(5)
b = np.arange(5)
c = np.arange(0,10,2)
def eq(a,b):
    if(len((a==b)[(a==b)==False])>0):
        print("no")
    else:
        print("yes")
eq(a,b)
eq(a,c)

yes
no


#### 28. Сделать массив неизменяемым

In [112]:
a = np.arange(10)
a = tuple(a)
a[0] = 1

TypeError: 'tuple' object does not support item assignment

#### 29. Найти n наибольших значений в массиве

In [86]:
n = 3
a = np.random.rand(100)
a.sort()
a[len(a)-n:]

array([0.96892159, 0.98055755, 0.98754448])

#### 30. Заменить максимальный элемент на ноль

In [87]:
a = np.random.rand(10)
a[a.argmax()] = 0

#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [124]:
P = np.zeros((3,3), dtype = [('x',float),('y',float)])
P['x'], P['y'] = np.meshgrid(np.linspace(0,1,3),np.linspace(0,1,3))
print(P)

[[(0. , 0. ) (0.5, 0. ) (1. , 0. )]
 [(0. , 0.5) (0.5, 0.5) (1. , 0.5)]
 [(0. , 1. ) (0.5, 1. ) (1. , 1. )]]


#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [148]:
x = np.array([1,2,3])
y = np.random.rand(3)
C = np.zeros((3,3)) 
for i in range(len(x)):
    C[::1,i] = 1/(x[::1]-y[i])
C

array([[5.0350275 , 1.07722912, 2.30451567],
       [0.83430067, 0.51858946, 0.69738379],
       [0.45483311, 0.34149418, 0.41085805]])

#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [160]:
for dtype in (np.int8, np.int32, np.int64):
    print("dtype =", dtype, "min =", np.iinfo(dtype).min)
    print("dtype =", dtype, "max =", np.iinfo(dtype).max)
for dtype in (np.float32, np.float64):
    print("dtype =", dtype, "min =", np.finfo(dtype).min)
    print("dtype =", dtype, "max =", np.finfo(dtype).max)

dtype = <class 'numpy.int8'> min = -128
dtype = <class 'numpy.int8'> max = 127
dtype = <class 'numpy.int32'> min = -2147483648
dtype = <class 'numpy.int32'> max = 2147483647
dtype = <class 'numpy.int64'> min = -9223372036854775808
dtype = <class 'numpy.int64'> max = 9223372036854775807
dtype = <class 'numpy.float32'> min = -3.4028235e+38
dtype = <class 'numpy.float32'> max = 3.4028235e+38
dtype = <class 'numpy.float64'> min = -1.7976931348623157e+308
dtype = <class 'numpy.float64'> max = 1.7976931348623157e+308


#### 34. Напечатать все значения в массиве

In [152]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [163]:
a = np.arange(100)
x = 17.1
i = (np.abs(a-x)).argmin()
a[i]

17

#### 36. Преобразовать массив из float в int

In [167]:
a = np.arange(10)
print(a)
a.astype(np.float32)

[0 1 2 3 4 5 6 7 8 9]


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

#### 37. Каков эквивалент функции enumerate для numpy массивов?

In [173]:
a = np.arange(9).reshape(3,3)
for i, val in np.ndenumerate(a):
    print(i, val)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. Случайно расположить p элементов в 2D массив

In [192]:
a = np.zeros((3,3))
p = 4
np.put(a,np.random.permutation(np.arange(5))[:p], 1)
a

array([[1., 0., 1.],
       [1., 1., 0.],
       [0., 0., 0.]])

#### 39. Отнять среднее из каждой строки в матрице

In [228]:
a = np.arange(9).reshape(3,3)
print(a)
print("means =", a.mean(axis=1, keepdims=True),sep='\n')
a-a.mean(axis=1, keepdims=True)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
means =
[[1.]
 [4.]
 [7.]]


array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

#### 40. Отсортировать матрицу по n-ому столбцу

In [241]:
a = np.random.rand(3,3)
n = 1 
print(a)
a[a[::1,n].argsort()]

[[0.41743211 0.5246095  0.26019957]
 [0.94202858 0.6245016  0.08874319]
 [0.01607972 0.25804197 0.20183683]]


array([[0.01607972, 0.25804197, 0.20183683],
       [0.41743211, 0.5246095 , 0.26019957],
       [0.94202858, 0.6245016 , 0.08874319]])

#### 41. Определить, есть ли в 2D массиве нулевые столбцы

In [290]:
a = np.random.randint(0,2,(3,3))
print(a)
print((~a.any(axis=0)).any())

[[0 0 0]
 [0 0 0]
 [0 1 1]]
True


#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [307]:
a = np.ones(5)
b = np.random.randint(0,len(a),5)
print(a)
print(b)
a[np.unique(b)]+=1
print(a)

[1. 1. 1. 1. 1.]
[1 4 0 0 0]
[2. 2. 1. 1. 2.]


#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [ ]:
#???

#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [324]:
a = np.random.randint(0,10, (3,4,3,4))
a.reshape(a.shape[:-2] + (-1,)).sum(axis=-1)

array([[58, 41, 41, 52],
       [63, 52, 43, 60],
       [62, 53, 42, 55]])